name: sheth-bench

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: 
        make build-wasm
    - name: Run benchmark
      run: 
        cargo bench --bench execution -- --noplot --sample-size=10 
